#!/usr/bin/env node
/**
 * 生成 public/sitemap.xml：
 *   npm run gen:sitemap   （SITE_URL 环境变量可覆盖站点地址）
 *
 * 原理：用 vite 内置的 rolldown 把 scripts/_sitemap-entry.ts 打包后在 Node 执行，
 * 拿到与线上渲染完全同源的资源 id 与分类 slug 全集，生成 hash 路由 URL 清单。
 * CI 在 build 前重新生成，保证 sitemap 与数据同步。
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = process.env.SITE_URL ?? 'https://openbox-13o.pages.dev';

const { rolldown } = await import('rolldown');
const bundle = await rolldown({
  input: join(ROOT, 'scripts/_sitemap-entry.ts'),
  platform: 'node',
});
const { output } = await bundle.generate({ format: 'cjs' });
await bundle.close();

// 执行打包产物，捕获 console.log 输出（入口会打印一行 JSON）
const tmpDir = join(ROOT, 'node_modules/.cache');
await mkdir(tmpDir, { recursive: true });
const tmpFile = join(tmpDir, 'sitemap-entry.cjs');
await writeFile(tmpFile, output[0].code);

let json = '';
const origLog = console.log;
console.log = (...a) => {
  json += a.join(' ');
};
try {
  await import(pathToFileURL(tmpFile));
} finally {
  console.log = origLog;
}
const data = JSON.parse(json.trim());

const today = data.updatedAt;
const urls = [
  { loc: `${SITE}/`, priority: '1.0', freq: 'daily' },
  ...data.subs.map((s) => ({ loc: `${SITE}/#/category/${s}`, priority: '0.8', freq: 'weekly' })),
  ...data.ids.map((id) => ({ loc: `${SITE}/#/resource/${id}`, priority: '0.6', freq: 'weekly' })),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<!-- ${urls.length} urls · generated by scripts/gen-sitemap.mjs · ${today} -->
${urls
  .map(
    (u) => `  <url>
    <loc>${u.loc}</loc>
    <changefreq>${u.freq}</changefreq>
    <priority>${u.priority}</priority>
    <lastmod>${today}</lastmod>
  </url>`,
  )
  .join('\n')}
</urlset>
`;

writeFileSync(join(ROOT, 'public/sitemap.xml'), xml);
console.log(`[gen-sitemap] 写入 ${urls.length} 条 URL（首页 + ${data.subs.length} 分类 + ${data.ids.length} 资源）`);
